# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c999f7092da0e33bf2146bbd14b256c6d44623a65e79167ad90d8113762da14995d12f0cdb84dcc9f987d3cc245275247e742b4ad50b93d682b53869aee1fd15

test:
  secret_key_base: 8b375de3f0a4ac38d4bd40dd8bd41f6a2946c8ba794b1ee75510534f7d1eeb1f9f1e3ebbf7ca74e0d3583f61cca7eaec6c4ecf5fe3d5ca2802dbfe4f7458a01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
